CREATE DATABASE CLINICA;
GO 

USE CLINICA;
GO

CREATE TABLE CLINICA(
	idClinica INT PRIMARY KEY IDENTITY(1,1),
	NomeClinica VARCHAR(30) NOT NULL,
	Endereço VARCHAR(1) NOT NULL UNIQUE
);
GO

CREATE TABLE VETERINARIO(
	idVeterinario INT PRIMARY KEY IDENTITY(1,1),
	idClinica INT FOREIGN KEY REFERENCES Clinica(idClinica),
	NomeVeterinario VARCHAR(10)
);
GO

CREATE TABLE DONO(
	idDono INT PRIMARY KEY IDENTITY(1,1),
	NomeDono VARCHAR(1)
);
GO

CREATE TABLE TIPODOPET(
	idTIPODOPET INT PRIMARY KEY IDENTITY(1,1),
	NomeTIPODOPET VARCHAR(20)
);
GO

CREATE TABLE RAÇA(
	IdRaça INT PRIMARY KEY IDENTITY(1,1),
	IdTipoPet INT FOREIGN KEY REFERENCES TIPODOPET(idTIPODOPET),
	NomeRaça VARCHAR(30)
);
GO

CREATE TABLE Pet(
	IdPet INT PRIMARY KEY IDENTITY(1,1),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdRaça INT FOREIGN KEY REFERENCES Raça(IdRaça),
	NomePet VARCHAR(10),
	DataNascimento DATETIME
);
GO

CREATE TABLE CONSULTA(
	idConsulta INT PRIMARY KEY IDENTITY(1,1),
	idVeterinario INT FOREIGN KEY REFERENCES Veterinario(idVeterinario),
	idPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	DataAtendimento DATETIME
);
GO