CREATE DATABASE CLINICA2;
GO

USE CLINICA2;
GO

CREATE TABLE CLINICA2 (
	IdClinica INT PRIMARY KEY IDENTITY(1,1),
	NomeClinica VARCHAR(50) NOT NULL,
	NomeEndereço VARCHAR(50) NOT NULL UNIQUE,
);
GO

CREATE TABLE VETERINARIOO (
	IdVeterinario INT PRIMARY KEY IDENTITY(1,1),
	IdClinica INT FOREIGN KEY REFERENCES CLINICA2 (IdClinica),
	NomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE DONOO (
	IdDono INT PRIMARY KEY IDENTITY(1,1),
	NomeDono VARCHAR(20)
);
GO

CREATE TABLE TIPODOPETT (
	IdTipoPet INT PRIMARY KEY IDENTITY(1,1),
	NomeTipoDoPet VARCHAR(20)
);
GO

CREATE TABLE RAÇAA (
	IdRaça INT PRIMARY KEY IDENTITY(1,1),
	IdTipoDoPet INT FOREIGN KEY REFERENCES TIPODOPETT (IdTipoDoPet),
	NomeRaça VARCHAR(30)
);
GO

CREATE TABLE PETT(
	IdPet INT PRIMARY KEY IDENTITY(1,1),
	IdDono INT FOREIGN KEY REFERENCES DONOO (IdDono),
	IdRaça INT FOREIGN KEY REFERENCES RAÇAA (IdRaça),
	NomePet VARCHAR(20),
	DataNascimento DATE
);
GO

CREATE TABLE CONSULTAA(
	IdConsulta INT PRIMARY KEY IDENTITY(1,1),
	IdVeterinario INT FOREIGN KEY REFERENCES VETERINARIOO (IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES PETT (IdPet),
	DataAtedimento DATETIME,
);
GO